<?php

class PrestaShopFeedTypes
{
    public static function getTypes()
    {
        return array(
            'product' => 'Product',
            'category' => 'Category',
            'manufacturer' => 'Manufacturer',
            'supplier' => 'Supplier',
            'combination' => 'Combination',
            'attribute' => 'Attribute',
            'attribute_group' => 'Attribute Group',
            'feature' => 'Feature',
            'feature_value' => 'Feature Value',
            'customer' => 'Customer',
            'address' => 'Address',
            'order' => 'Order',
            'order_detail' => 'Order Detail',
            'order_state' => 'Order State',
            'tax_rules' => 'Tax Rules',
            'zone' => 'Zone',
            'currency' => 'Currency',
            'country' => 'Country',
            'state' => 'State',
            'warehouse' => 'Warehouse',
            'stock_movement' => 'Stock Movement',
            'supply_order' => 'Supply Order',
            'carrier' => 'Carrier',
            'shop' => 'Shop',
            'shop_group' => 'Shop Group',
            'cms' => 'CMS',
            'cms_category' => 'CMS Category',
            'store' => 'Store',
            'contact' => 'Contact',
            'meta' => 'Meta',
            'tax' => 'Tax',
            'attachment' => 'Attachment',
            'cart_rule' => 'Cart Rule',
            'specific_price_rule' => 'Specific Price Rule',
            'specific_price' => 'Specific Price',
            'image' => 'Image',
            'customization' => 'Customization',
            'customization_field' => 'Customization Field',
            'group' => 'Group',
            'alias' => 'Alias',
            'tag' => 'Tag',
            'attribute_lang' => 'Attribute Lang',
            'attribute_group_lang' => 'Attribute Group Lang',
            'feature_lang' => 'Feature Lang',
            'feature_value_lang' => 'Feature Value Lang',
            'supplier_lang' => 'Supplier Lang',
            'manufacturer_lang' => 'Manufacturer Lang',
            'product_lang' => 'Product Lang',
            'category_lang' => 'Category Lang',
            'cms_lang' => 'CMS Lang',
            'cms_category_lang' => 'CMS Category Lang',
            'store_lang' => 'Store Lang',
            'tag_lang' => 'Tag Lang',
            'carrier_lang' => 'Carrier Lang',
            'meta_lang' => 'Meta Lang',
            'stock_available' => 'Stock Available',
            'shop_url' => 'Shop URL',
            'order_invoice' => 'Order Invoice',
            'order_invoice_detail' => 'Order Invoice Detail',
            'order_message' => 'Order Message',
            'order_message_lang' => 'Order Message Lang',
            'order_return' => 'Order Return',
            'order_return_detail' => 'Order Return Detail',
            'order_slip' => 'Order Slip',
            'order_slip_detail' => 'Order Slip Detail',
            'order_payment' => 'Order Payment',
        );
    }
}
